### ISSUE TITLE
Cannot see redux store in the additional data section in Sentry

### ISSUE THREAD

**Issue by jelaxshan** [vidit-sh/redux-sentry-middleware#12]
```
import * as Sentry from '@sentry/browser';
import * as createSentryMiddleware from 'redux-sentry-middleware';
import { combineReducers, createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import reducers from './reducers';

export const store = createStore(
  reducers,
  composeWithDevTools(
    applyMiddleware(
      createSentryMiddleware(Sentry),
    ),
  ),
); 

```

Using typescript. Am I doing something wrong here in the setup?

**Comment by sandinosaso** [comment]
Would you please format this to better reading ??
```createSentryMiddleware(Sentry, {})``` works for you ?

Another thing is strange `composeWithDevTools()` returns a function, so you should call something like this:

```javascript
const composeEnhancers = composeWithDevTools({
  // options like actionSanitizer, stateSanitizer
});
const middlewares = [
 createSentryMiddleware(Sentry)
];
const store = createStore(reducer, composeEnhancers(
  applyMiddleware(...middlewares),
));
```

**Comment by cyrilchapon** [comment]
?

**Comment by vidit-sh** [comment]
@jelaxshan by the look, nothing seems wrong here. 
Did you get Sentry running in your app? As in are you able to capture exceptions?

**Comment by jelaxshan** [comment]
I got sentry working, but not seeing the redux state in the additional data section

**Comment by jelaxshan** [comment]
Seems to be working now. I initialised Sentry in another file before, so have added the initialisation step in the same file. Rookie mistake

**Comment by gaurav5430** [comment]
what was your exact problem here ? 

I am facing something similar

**Comment by gaurav5430** [comment]
got the issue in my case, I was calling and adding the middleware before initializing Sentry
