### ISSUE TITLE
Usage with react native

### ISSUE THREAD

**Issue by snobear** [vidit-sh/redux-sentry-middleware#16]
Hi I'm trying to ship redux state breadcrumbs with react native. Breadcrumbs are being sent, but they all show up in Sentry as just `POST http://localhost:8081/symbolicate [200]`. Screenshot:

![image](https://user-images.githubusercontent.com/696230/73026435-65acce00-3dff-11ea-9c58-bbb4356c91b1.png)

My store looks like:

```
import thunk from 'redux-thunk';
import { createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import rootReducer from '../reducers';
import config from '../config/config';
import * as Sentry from '@sentry/react-native';
import createSentryMiddleware from "redux-sentry-middleware";

let middleware = [thunk];
let sentryUrl = config.sentry.projectUrl;

if (sentryUrl) {
  Sentry.init({
    dsn: sentryUrl
  });
  const middleware = [thunk, createSentryMiddleware(Sentry)];
} else {
  console.warn('config.sentry.projectUrl not set. Sentry not initialized.');
}

const initialState = {};

// rootReducer is the combined reducers
const store = createStore(rootReducer, initialState, composeWithDevTools(
  applyMiddleware(...middleware)
));

export default store;
```

We were using [raven-for-redux](https://github.com/captbaritone/raven-for-redux), so trying to migrate to `redux-sentry-middleware`.

I'm testing on the iOS Simulator, so perhaps thats the issue.

**Comment by vidit-sh** [comment]
@snobear I see a bug in your code above, something to do with the middlewares being applied to your store. Can you figure it out?

**Comment by vidit-sh** [comment]
@snobear please close the thread once you figure out the issue.
Let me know if I could help you.

**Comment by snobear** [comment]
Hi @vidit-sh  I'm not sure I see the bug. Is it necessary to pass the options object, even if its an empty `{}` object?

```
        createSentryMiddleware(Sentry, {
            // Optionally pass some options here.
        })
```

**Comment by snobear** [comment]
Oh I do see that I'm initializing middleware with `let middleware =` but then calling `const middleware` in the conditional. That could be it. I'll test that out later.

**Comment by vidit-sh** [comment]
Bingo 👍

**Comment by snobear** [comment]
Ok thanks for the clue. You can close this now and I'll reopen if I need any help after that.
