### ISSUE TITLE
redux state not serialised correctly

### ISSUE THREAD

**Issue by ebaioni** [vidit-sh/redux-sentry-middleware#17]
Hi there,
first of all, thank you for building this middleware.
I'm having an issue in which my redux state in not serialised correctly past the first level.
Any idea what I am missing?
<img width="514" alt="Screen Shot 2020-02-19 at 9 26 46 am" src="https://user-images.githubusercontent.com/2899310/74793613-f26e7d00-5314-11ea-8fcb-f20ccb2c3043.png">

**Comment by kltchnko** [comment]
@ebaioni Hi, I had the same issue. It is about your init settings of Sentry SDK. Firslty, I tried to add ExtraErrorData integration but it didn't help. After that I updated "@sentry/browser" to 5.12.4 and added `normalizeDepth: 10` to Sentry.init() options and it worked!
See [2417](https://github.com/getsentry/sentry-javascript/issues/2417)
