### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tony** [vidit-sh/redux-sentry-middleware#21]
Hi @vidit-sh! Thank you for the project!

Between 0.1.3 and 0.1.8, can the changelog be filled in?

(I assume they were just security package pinnings?)

**Comment by vidit-sh** [comment]
@tony nothing major, just security updates in some packages

**Comment by tony** [comment]
@vidit-sh Hey thank you!

If it involves publishing a package update to NPM, do you think warrants noting it in the changelog?

Hm - put it this way - even if it's not major - it was important enough to bump the package version for. The changelog can note what is was.

Also take this with a grain of salt - I'm used to package updates mentioning what happened between versions - even if it's just dev dependency updates. :shrug:

**Comment by tony** [comment]
@vidit-sh Hi there, can you please update the changelog so it reflects the published npm packages?
