### ISSUE TITLE
Changelog / Release notes?

### ISSUE THREAD

**Issue by tony** [vidit-sh/redux-sentry-middleware#9]
Hi, thank you for the project @vidit-sh!

Do we want to keep a CHANGES.md file or add a list of changes to github releases?

(Was wondering what changed between versions, sometimes git logs work, but it's
helpful to know why the maintainer(s) decided to make the release in their own words
and what happened in between)

**Comment by vidit-sh** [comment]
Hey tony, thanks for pointing it out. This me being naive and lazy. 
Will add release notes soon. 😊

**Comment by tony** [comment]
@vidit-sh Good to know! Thanks again for the project 😊

**Comment by Vages** [comment]
Hi! Just want to repeat this request. If you'd like to, I could put up a few dollars on issuehunt to have this in place: https://issuehunt.io/
